### ISSUE TITLE
get rid of top level amdloader "task"?

### ISSUE THREAD

**Issue by wkeese** [ibm-js/grunt-amd-build#15]
I find it confusing that there's a task called "amdloader", except it isn't really a task but configuration options.  I.E. IIUC you can't say "grunt amdloader" even though "amdloader" is defined just like the other tasks (ex: amdbuild, intern, jshint).

Relatedly, it took me a while to figure out that you need to type "grunt amdbuild:amdloader" rather than just "grunt amdbuild".

Is there a reason and/or precedent for defining the loader configuration options globally, rather than inside the amdbuild target, like this?

```
amdbuild: {
	loader: {
		// Everything should be relative to baseUrl
		baseUrl: "./",

		// Enable build of requirejs-text/text
		inlineText: true,

		// Here goes the config for the amd plugins build process (has, i18n, ecma402...).
		config: {}
	},
	
	// dir is the output directory.
	dir: tmpdir,

	// List of plugins that the build should not try to resolve at build time.
	runtimePlugins: [],

	// List of layers to build.
	layers: [{
		name: "layerName",
		include: [
			// Modules and layers listed here, and their dependencies, will be added to the layer.
		],
		includeShallow: [
			// Only the modules listed here (ie. NOT their dependencies) will be added to the layer.
		],
		exclude: [
			// Modules and layers listed here, and their dependencies, will NOT be in the layer.
		],
		excludeShallow: [
			// Only the modules listed here (ie. NOT their dependencies)  will NOT be in the layer.
		]
	}]
},
```

**Comment by clmath** [comment]
I have actually seen a use case for the amdloader top level configuration. It allows to easily build two layers with different loader configuration. 

So I'am closing as wont'fix for now but feel free to continue the discussion.
