### ISSUE TITLE
Amdserialize write files outside of tmp directory if the baseUrl start with "../"

### ISSUE THREAD

**Issue by clmath** [ibm-js/grunt-amd-build#16]
Currently the amdserialize task output files to `"tmp/" + baseUrl + modulePath` which, if baseUrl is `../` and if the modulePath within baseUrl is `foo.js`, leads to `tmp/../foo.js` then to `foo.js`.

Before finding a way to solve this, it would be good to know how `r.js` and the dojo build behave in similar situation.

One solution that is NOT good is amdserialize outputing files to `"tmp/" + moduleId + ".js"` as that would break the use of `require.toUrl` in the `writeFile` function of plugins. (see http://www.requirejs.org/docs/plugins.html#apiwritefile)

**Comment by cjolif** [comment]
please add some doc about that.

**Comment by clmath** [comment]
Leading `../` in baseUrl are now removed before writing the file to the tmp directory. 

Access to directories above `baseUrl` without path configuration can still result in files written outside of tmp directory but this should not be done. You should use path config when working with files outside baseUrl.
